version: '3.7'

services: 
    backend:
        build: ./backend
        volumes:
            - ./backend/:/app/
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=./app.py
            - DATABASE_URL=postgresql://admin:Password1!@db:5432/backend
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=Password1!
            - POSTGRES_DB=backend

volumes: 
    postgres_data: